### ISSUE TITLE
{page: n} ignored (not added to URL) in ngx-resource 3.0.1

### ISSUE THREAD

**Issue by siovene** [troyanskiy/ngx-resource#118] opened 2017-06-07 08:00 UTC
I attempted to migrate a project from the `ngx-resource 2.1.1` to `3.0.1`, and after fixing the naming convention breakage (functions now prepended with `$`) I noticed that the `{page: n}` argument is not working anymore.

Here's some relevant code:

```typescript
import { Injectable } from '@angular/core';
import { Resource, ResourceAction, ResourceMethod, ResourceParams} from 'ngx-resource';

export class RestClient extends Resource {
    private token: string = null;

    public setToken(token: string) {
        this.token = token;
    }

    public $getHeaders(methodOptions?: any): any {
        let headers = super.$getHeaders();
        headers.Authorization = 'token ' + this.token;
        return headers;
    }
}

export interface IQueryInput {
  page?: number;
  perPage?: number;
}

@Injectable()
@ResourceParams({
  url: 'https://api.github.com/user'
})
export class GitHubUserService extends RestClient {
  @ResourceAction({
    isArray: true,
    path: '/repos'
  })
  getRepos: ResourceMethod<IQueryInput, any[]>;
}
```

Which gets used like this:

```typescript
this.gitHubUserService.getRepos({page: page}).$observable.subscribe((repos: any[]) => {
  // do something with the repos
});
```

This exact code (minus the new `$` naming convention) was working fine with `2.1.1` and something like `?page=1` was appended to the request URL. This is not happening anymore in `3.0.1`.

**Comment by desfero** [comment] 2017-06-07 15:43
duplicate of https://github.com/troyanskiy/ngx-resource/issues/116

**Comment by troyanskiy** [comment] 2017-06-07 19:24
@siovene What angular version do you have?

**Comment by troyanskiy** [comment] 2017-06-07 19:30
Please check answer on #116

**Closed by troyanskiy** 2017-06-07 19:30 UTC
